server:
  port: 80
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
    register-with-eureka: false
spring:
  application:
    name: consumer-feign-order-service
ribbon:
  #指的是建立连接所用时间,适用于网络状况正常情况下,两端连接所用时间
  ReadTimeout:  5000
  #指的是建立连接后从服务器读取可用资源所用时间
  ConnectTimeout: 5000
  # Max number of retries on the same server (excluding the first try)
  MaxAutoRetries: 1
  # Max number of next servers to retry (excluding the first server)
  MaxAutoRetriesNextServer: 1
  #是否开启重试 默认false 只对get重试
  OkToRetryOnAllOperations: false
logging:
  level:
    com.springcloud.service.PaymentFeignService: debug
